### ISSUE TITLE
Can't seem to work with crss: doesn't seem to be properly read

### ISSUE THREAD

**Issue by reinvantveer** [perliedman/reproject#11]
Hi!

Can you perhaps shed some light on why
```javascript
function toWGS84(geojson) {
    var crss = {
        "EPSG:28992": proj4.Proj("+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.237,50.0087,465.658,-0.406857,0.350733,-1.87035,4.0812 +units=m +no_defs")
    };

    return reproject.toWgs84(geojson, "EPSG:28992", crss);
}
```
throws error
```
TypeError: Cannot read property 'EPSG:28992' of undefined
    at determineCrs (data-bag/node_modules/reproject/index.js:67:17)
    at reproject (data-bag/node_modules/reproject/index.js:77:12)
    at Object.module.exports.toWgs84 (data-bag/node_modules/reproject/index.js:130:14)
    at Object.toWGS84 (data-bag/bag.js:264:22)
    at Context.<anonymous> (data-bag/test/test.js:140:27)
```
Please?

**Comment by reinvantveer** [comment]
Perhaps I'm using this the wrong way, but it's hard to find examples.

**Comment by perliedman** [comment]
Thanks for reporting! Turned out to be a parameter missing in the `toWgs84` function.

I've committed a fix and released version 1.0.1 which contains the fix.

**Comment by reinvantveer** [comment]
Handy! I'll check it out

Op vr 5 feb. 2016 10:47 schreef Per Liedman <notifications@github.com>:

**Comment by Razpudding** [comment]
Thanks for asking this question Rein. I couldn't find examples of how to pass in a crss and your code finally made it click for me 🙏🏼
